### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by atultaz** [solana-developers/dapp-scaffold-react-native#1]
Hey I just started but my iOS build could not complete.
`info Found Xcode workspace "SolanaDappScaffold.xcworkspace"
info Building (using "xcodebuild -workspace SolanaDappScaffold.xcworkspace -configuration Debug -scheme SolanaDappScaffold -destination id=4A2162B8-BD21-4C90-8326-F547904307A0")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening SolanaDappScaffold.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace SolanaDappScaffold.xcworkspace -configuration Debug -scheme SolanaDappScaffold -destination id=4A2162B8-BD21-4C90-8326-F547904307A0

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: 03d04c9529f107bc613edf5c7f811cbd
Build description path: /Users/atultiwari/Library/Developer/Xcode/DerivedData/SolanaDappScaffold-afbscgvrqtimslggijhpycajkfpo/Build/Intermediates.noindex/XCBuildData/03d04c9529f107bc613edf5c7f811cbd-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
/Users/atultiwari/Desktop/solana react native/dapp-scaffold-react-native/ios/Pods/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold.debug.xcconfig:1:1: error: unable to open file (in target "SolanaDappScaffold" in project "SolanaDappScaffold")
/Users/atultiwari/Desktop/solana react native/dapp-scaffold-react-native/ios/Pods/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold.debug.xcconfig:1:1: error: unable to open file (in target "SolanaDappScaffold" in project "SolanaDappScaffold")
/Users/atultiwari/Desktop/solana react native/dapp-scaffold-react-native/ios/Pods/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold.debug.xcconfig:1:1: error: unable to open file (in target "SolanaDappScaffold" in project "SolanaDappScaffold")
/Users/atultiwari/Desktop/solana react native/dapp-scaffold-react-native/ios/Pods/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold.debug.xcconfig:1:1: error: unable to open file (in target "SolanaDappScaffold" in project "SolanaDappScaffold")
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold-frameworks-Debug-output-files.xcfilelist' (in target 'SolanaDappScaffold' from project 'SolanaDappScaffold')
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold-resources-Debug-output-files.xcfilelist' (in target 'SolanaDappScaffold' from project 'SolanaDappScaffold')
error: Unable to load contents of file list: '/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold-frameworks-Debug-input-files.xcfilelist' (in target 'SolanaDappScaffold' from project 'SolanaDappScaffold')
error: Unable to load contents of file list: '/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold-frameworks-Debug-output-files.xcfilelist' (in target 'SolanaDappScaffold' from project 'SolanaDappScaffold')
error: Unable to load contents of file list: '/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold-resources-Debug-input-files.xcfilelist' (in target 'SolanaDappScaffold' from project 'SolanaDappScaffold')
error: Unable to load contents of file list: '/Target Support Files/Pods-SolanaDappScaffold/Pods-SolanaDappScaffold-resources-Debug-output-files.xcfilelist' (in target 'SolanaDappScaffold' from project 'SolanaDappScaffold')

2022-04-22 14:22:58.901 xcodebuild[4663:146065] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-04-22 14:22:58.901 xcodebuild[4663:146065] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **

info Run CLI with --verbose flag for more details.`

**Comment by beeman** [comment]
Could you try and run the base template to see if that does work?

https://github.com/react-native-community/react-native-template-typescript

**Comment by atultaz** [comment]
thanks mate
